[package]
name = "kicad-wrapper"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
color-eyre = "0.6.5"
ignore = "0.4.23"
thiserror = "2.0.16"
tokio = { version = "1.48.0", features = ["full"] }
